exclude: "^LICENSE"

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ["--maxkb=2000"]

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.7.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, "2", --preserve-quotes]

- repo: https://github.com/snakemake/snakefmt
  rev: v0.8.1
  hooks:
  - id: snakefmt
