file: "https://tubcloud.tu-berlin.de/s/m73a6SGXEYAsiyY/download/network-assignment-5.nc"

trials: 2

scenarios:
  resolution:
    - 2
    - 3
    - 4
    - 5

forbidden:
  - 1.4.0.dev0

# solver_options:
#   solver: ipm
#   parallel: on
#   run_crossover: off